MODEL:
  TYPE: mbanynet
  NUM_CLASSES: 1000
ANYNET:
  STEM_TYPE: res_stem_in
  STEM_W: 64
  BLOCK_TYPE: res_bottleneck_block
  STRIDES: [[1, 1, 1], [2, 2, 2], [2, 2, 2], [2, 2, 2]]
  DEPTHS: [[2, 2, 2], [3, 4, 3], [4, 5, 3], [2, 2, 2]]
  WIDTHS: [[128, 128, 160], [320, 256, 256], [576, 448, 448], [1344, 1120, 736]]
  BOT_MULS: [0.25, 0.25, 0.25, 0.25]
  GROUP_WS: [[32, 32, 40], [80, 64, 64], [144, 112, 112], [336, 280, 184]]
  DEVICES: ["cpu", "dsp", "gpu"]
  HEAD_DEVICE: "cpu"
  STEM_DEVICE: "cpu"
  MERGE_DEVICE: "cpu"
  ORIGINAL_WIDTHS: [416, 832, 1472, 3200]
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.2
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 256
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 200
  POWERSAVE_LEVEL: 255
NUM_GPUS: 8
OUT_DIR: .
